repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.241  # Update this version as needed.
    hooks:
      - id: ruff
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.971  # Update this version as needed.
    hooks:
      - id: mypy
  - repo: https://github.com/psf/black
    rev: 23.3.0  # Update this version as needed.
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.12.0  # Update this version as needed.
    hooks:
      - id: isort
